n_clusters:
  desc: Number of clusters to search for
  value: 17
dataset:
  desc: Which dataset to load. Could be sen1 | sen2
  value: 'sen1'
subset:
  desc: Which subset to laod (validation|training)
  value: 'training'
datapath:
  desc: Where the data is located
  value: '/pfs/work7/workspace/scratch/ih5525-BigDataTools_HeAT-0/data/'
metric:
  desc: Which metric to use for the clustering to construct the similarity matrix (rbf|euclidean)
  value: 'rbf'
gamma:
  desc: Kernel coefficient sigma for rbf
  value: 3.0
laplacian:
  desc: How to calculate the graph laplacian (affinity) ('fully_connected', 'eNeighbour')
  value: 'fully_connected'
threshold:
  desc:  Threshold for affinity matrix if laplacian='eNeighbour' Ignorded for laplacian='fully_connected'
  value: 1.0
boundary:
  desc: How to interpret threshold (upper|lower)
  value: 'upper'
n_lanczos:
  desc: number of Lanczos iterations for Eigenvalue decomposition
  value: 300
assign_labels:
  desc: The strategy to use to assign labels in the embedding space
  value: 'kmeans'
dataset_percentage:
  desc: Take part of the dataset (1.0 for full dataset)
  value: 0.4
weak_scaling_max:
  desc: If not 0 uses int as max for weak scaling and overwrites dataset_percentage
  value: 32
num_fittings:
  desc: Change the number of fittings that should be performed. Useful for profiling the fitting function
  value: 3
normalize:
  desc: Activate to enable normalization of the data before clustering
  value: False
